### ISSUE TITLE
TF-021. Idle vs Active state

### ISSUE THREAD

**Issue by kennethfinn** [Heatit-Controls/no.ThermoFloor#37]
For me this app is missing some basic elements. The Heatit Z-wave thermostat (TF-021) obviously give a state to the app if the thermostat is active or idle. I just dont undersrand why this basic state and information is not utilized in the app? Please don't mix my request with thermostat on/off.

1. I need a trigger card and a condition card for my flows to to pick up changes in the state and the condition the state. That is crucial and basic.

2. Also in the app. I would request to utilize the two states to predefine fixed power consumption for active and another for idle. Like you can find in apps for plugs, switches and bulbs. If you then know the power of you heating elements you can mimic power reading from the thermostat even though it is not supported.

Please advise if I have missed something in my home work 😊

**Comment by Thunstop** [comment]
Same problem here, just installed heatit TF 021 and it does not report when it's idle or heating but history tab does show when it turned on or off. Which means it can't be hard to fix it.

And because incorrect idle state, constant power consumption possible to insert in advance settings makes the sensor report power consumption even when the not active.

This also makes it hard to get analysis of when the thermostat is active or not thought the day. 

Please can you look into this.
